USE UNIVER

SELECT AUDITORIUM.AUDITORIUM[Номер аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPE[Тип аудиторий]
FROM AUDITORIUM Inner Join AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE