USE UNIVER;

CREATE TABLE TABLEA( ID INT, IDVALUE NVARCHAR(20));
INSERT INTO TABLEA(ID,IDVALUE)
VALUES(1,'A'),(2,'B'), (3, 'C');

CREATE TABLE TABLEb( ID INT, IDVALUE NVARCHAR(20));
INSERT INTO TABLEA(ID,IDVALUE)
VALUES(4,'D'),(5,'E'), (6, 'F');

SELECT *
FROM TABLEA FULL OUTER JOIN TABLEb
ON TABLEA.ID = TABLEb.ID;

SELECT TABLEA.*
FROM TABLEA FULL OUTER JOIN TABLEb
ON TABLEA.ID = TABLEb.ID
WHERE TABLEb.ID IS NULL;

SELECT TABLEb. *
FROM TABLEA FULL OUTER JOIN TABLEb
ON TABLEA.ID = TABLEb.ID
WHERE TABLEA.ID IS NULL;

SELECT *
FROM TABLEA FULL OUTER JOIN TABLEb
ON TABLEA.ID = TABLEb.ID
WHERE TABLEA.ID IS NOT NULL AND TABLEb.ID IS NOT NULL;


