USE UNIVER
SELECT STUDENT.NAME [Студент], STUDENT.IDGROUP [Группа],
CASE WHEN PROGRESS.NOTE BETWEEN 0 AND 3 THEN 'плохо'
WHEN PROGRESS.NOTE BETWEEN 4 AND 6 THEN 'хорошо'
WHEN PROGRESS.NOTE BETWEEN 7 AND 8 THEN 'отлично'
ELSE 'no'
END степень, COUNT(*)[количество]
FROM STUDENT, PROGRESS WHERE STUDENT.IDGROUP=4
GROUP BY STUDENT.NAME, STUDENT.IDGROUP,
CASE WHEN PROGRESS.NOTE BETWEEN 0 AND 3 THEN 'плохо'
WHEN PROGRESS.NOTE BETWEEN 4 AND 6 THEN 'хорошо'
WHEN PROGRESS.NOTE BETWEEN 7 AND 8 THEN 'отлично'
ELSE 'no'
END