CREATE TABLE #NEW(age INT,NAME VARCHAR(50),id INT)
DECLARE @ii INT=0;
WHILE @ii<10
BEGIN
INSERT #NEW(age, name, id) VALUES (FLOOR(24*RAND()), REPLICATE('что-то',2), FLOOR(26*RAND()));
SET @ii=@ii+1;
END
SELECT * FROM #NEW



