BEGIN TRY
  DECLARE @Err INT;
  SELECT @Err = 1 / 0;
END TRY
BEGIN CATCH
  PRINT ERROR_NUMBER()
  PRINT ERROR_MESSAGE()
  PRINT ERROR_LINE()
  PRINT ERROR_PROCEDURE()
  PRINT ERROR_SEVERITY()
  PRINT ERROR_STATE()
END CATCH