CREATE VIEW [Количество кафедр]
AS SELECT FACULTY.FACULTY_NAME[Факультет], COUNT(*) [Количество кафедр]
FROM FACULTY INNER JOIN PULPIT
ON PULPIT.FACULTY = FACULTY.FACULTY
GROUP BY FACULTY.FACULTY_NAME