USE UNIVER;

SELECT AUDITORIUM.AUDITORIUM_TYPE,
MAX(AUDITORIUM.AUDITORIUM_CAPACITY)[MAX CAPACITY],
MIN(AUDITORIUM.AUDITORIUM_CAPACITY)[MIN CAPACITY],
AVG(AUDITORIUM.AUDITORIUM_CAPACITY)[AVG CAPACITY],
SUM(AUDITORIUM.AUDITORIUM_CAPACITY)[SUM CAPACITY],
COUNT(*)[COUNT]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM.AUDITORIUM_TYPE