USE UNIVER;

SELECT FACULTY, PROFESSION, SUBJECT,
ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2) [AVG_NOTE]
FROM PROGRESS INNER JOIN STUDENT
ON STUDENT.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY = 'рнб'
GROUP BY FACULTY, PROFESSION, SUBJECT