USE UNIVER;

SELECT *
FROM(SELECT CASE 
WHEN NOTE BETWEEN 1 AND 2 THEN '1-2'
WHEN NOTE BETWEEN 3 AND 4 THEN '3-4'
WHEN NOTE BETWEEN 5 AND 6 THEN '5-6'
WHEN NOTE BETWEEN 7 AND 9 THEN '7-9'
ELSE '10'
END[Œ÷≈Õ »], COUNT(*)[ ŒÀ-¬Œ]
FROM PROGRESS GROUP BY CASE
WHEN NOTE BETWEEN 1 AND 2 THEN '1-2'
WHEN NOTE BETWEEN 3 AND 4 THEN '3-4'
WHEN NOTE BETWEEN 5 AND 6 THEN '5-6'
WHEN NOTE BETWEEN 7 AND 9 THEN '7-9'
ELSE '10'
END) AS T
ORDER BY CASE[Œ÷≈Õ »]
WHEN '1-2'THEN 4
WHEN '3-4' THEN 3
WHEN '5-6' THEN 2
WHEN '7-9' THEN 1
ELSE 0
END