USE UNIVER;

SELECT AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM aud1
WHERE AUDITORIUM_CAPACITY=(SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aud2
WHERE aud2.AUDITORIUM_NAME = aud1.AUDITORIUM_NAME
ORDER BY AUDITORIUM_CAPACITY DESC)