USE UNIVER;

SELECT TOP 1
(SELECT AVG(NOTE) FROM PROGRESS
WHERE SUBJECT LIKE 'нюХо'),
(SELECT AVG(NOTE) FROM PROGRESS
WHERE SUBJECT LIKE 'ад '),
(SELECT AVG(NOTE) FROM PROGRESS
WHERE SUBJECT LIKE 'ясад')

FROM PROGRESS