USE UNIVER;

SELECT GROUPS.FACULTY [FACULTY], GROUPS.PROFESSION [PROFESSION], PROGRESS.SUBJECT [PROGRESS],
ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2) [AVG]
FROM GROUPS, STUDENT, PROFESSION, PROGRESS
WHERE GROUPS.FACULTY IN ('рнб')
GROUP BY CUBE (GROUPS.FACULTY, GROUPS.PROFESSION,PROGRESS.SUBJECT);