USE UNIVER;

SELECT GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT,
ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2) 
FROM GROUPS, STUDENT, PROFESSION, PROGRESS
WHERE GROUPS.FACULTY IN ('рнб')
GROUP BY ROLLUP (GROUPS.FACULTY, GROUPS.PROFESSION,PROGRESS.SUBJECT);