USE UNIVER;

SELECT	GROUPS.PROFESSION [PROFESSION],PROGRESS.SUBJECT [PROGRESS],
round(avg(cast(PROGRESS.NOTE AS float(4))), 2) [AVG]
FROM GROUPS, STUDENT, PROFESSION, PROGRESS
WHERE GROUPS.FACULTY in ('“Œ¬')
GROUP BY GROUPS.FACULTY,
GROUPS.PROFESSION, 
PROGRESS.SUBJECT
INTERSECT
SELECT	
GROUPS.PROFESSION [PROFESSION],
PROGRESS.SUBJECT [PROGRESS],
round(avg(cast(PROGRESS.NOTE AS float(4))), 2) [AVG]
FROM GROUPS, STUDENT, PROFESSION, PROGRESS
WHERE GROUPS.FACULTY in ('’“Ë“')
GROUP BY GROUPS.FACULTY,
GROUPS.PROFESSION, 
PROGRESS.SUBJECT